---
name: Update dependent repositories
on:
  push:
    branches:
      - main
  workflow_run:
    types:
      - completed
    workflows:
      - 'automerge'
jobs:
  update-dependent-repositories:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push' && !startsWith(github.event.commits[0].message, '[github-actions]') }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["integration-k8s-kind"]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
